server:
  port: 7003

eureka:
  instance:
    hostname: eureka03.com
  client:
    #表示不向注册中心注册自己
    register-with-eureka: false
    #表示自己是注册中心，不去检索服务
    fetch-registry: false
    #与eureka交互的地址
    service-url:
      #单机版
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群版
      defaultZone: http://eureka02.com:7002/eureka/,http://eureka01.com:7001/eureka/